### ISSUE TITLE
Translation - DEPLOY doesn't work

### ISSUE THREAD

**Issue by yshish** [zooniverse/Translator#15]
Not sure whether this is the correct place for reporting. I've reported it to Darren already but not sure whether it's known for others: 

The "Deploy" feature doesn't work for any of the translators. It was used to take me to the (!)untranslated PW page. After some changes on the page I always get to this [page](http://www.undefined.com/?lang=./translations/237fcbb0a7d3f9e7.json) after clicking on the link. Some other translator says that DNS lookup failure appears when clicking the link (DNS_PROBE_FINISHED_NXDOMAIN). Any idea on why that may be? Could you please fix it? 

Many thanks!

**Comment by chrissnyder** [comment]
Does this happen on every project you try to translate or just PW?

**Comment by yshish** [comment]
I cannot see/access any other project to translate there however I
translated the Plankton Portal texts about two years ago (and I would like
to continue with translating the new PP texts). The only project which I
see there is the Penguin Watch.
Should I be able to see other projects there?
http://translations.zooniverse.org/#/projects
Please, give me at least an access to the Plankton P.

Thanks,
Z.

2015-05-26 16:43 GMT+02:00 Chris Snyder <notifications@github.com>:

**Comment by yshish** [comment]
Thanks for the access to the PP. Yes, it doesn't work only for the PW, all the texts appear in English there.

**Comment by yshish** [comment]
It seems to be a problem for the PW only. None of the languages displays after deploying.

**Comment by chrissnyder** [comment]
Closed in https://github.com/zooniverse/Penguins/commit/28ec25a46677d2bdbfd1b9881d848379a6c99415 Work still needs to be done to get translations onto PW, but the deploy should now work.
